package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "traversal_tree",
    srcs = [
        "traversal_tree.cpp",
    ],
    deps = [
        "//common:tree_node",
    ],
)

cc_binary(
    name = "226_invert_tree",
    srcs = [
        "invert_tree.cpp",
    ],
    deps = [
        "//common:tree_node",
    ],
)

cc_binary(
    name = "main",
    srcs = [
        "main.cpp",
    ],
    deps = [
        "//common:tree_node",
    ],
)
