package(default_visibility = ["//visibility:public"])
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "tree_node",
    srcs = [
      "tree_node.cpp",
    ],
    hdrs = [
      "tree_node.h",
    ],
    deps = [
      
    ],
)